export const IMAGES = [
  {
    src: "https://i.ibb.co/Yc4dyMr/106.jpg",
    thumbnail: "https://i.ibb.co/Yc4dyMr/106_thumb.jpg",
  },
  {
    src: "https://i.ibb.co/6rHKxg8/105.jpg",
    thumbnail: "https://i.ibb.co/6rHKxg8/105_thumb.jpg",
  },
  {
    src: "https://i.ibb.co/2sTBPdX/102.jpg",
    thumbnail: "https://i.ibb.co/2sTBPdX/102_thumb.jpg",
  },
  {
    src: "https://i.ibb.co/GJsyzb4/101.jpg",
    thumbnail: "https://i.ibb.co/GJsyzb4/101_thumb.jpg",
  },
  {
    src: "https://i.ibb.co/DzywQXn/103.jpg",
    thumbnail: "https://i.ibb.co/DzywQXn/103_thumb.jpg",
  },
  {
    src: "https://i.ibb.co/Q6sSWpY/104.jpg",
    thumbnail: "https://i.ibb.co/Q6sSWpY/104_thumb.jpg",
  },
  { src: "https://i.ibb.co/b2Hc9hM/img45.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/85wDnrq/img47.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/hDLmbN0/img58.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/Rzd4dtY/img59.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/cbsKq79/img60.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/nkwHwCq/img66.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/68Q2jxp/img67.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/MS8kf5c/img73.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/NZgsGCC/img75.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/NnHHKz0/img76.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/wwPtjks/img82.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/MB4jpJR/img83.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/fv7Bhvx/img88.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/Bn7C2jF/img91.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/3r3WxQm/img92.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/CHCksQW/img98.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/ZN7yzfJ/img102.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/2MBRyST/img106.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/4VdY02K/img107.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/xShnGsX/img108.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/LQ3FYb8/img43.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/yQh0Vhy/img44.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/dGbY6YX/img46.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/NLLxhGf/img48.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/YQVzyS2/img52.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/K5W0n3v/img53.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/k1fv5QV/img54.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/0JD7jZR/img61.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/ng36DQ9/img65.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/DCHyvp6/img68.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/6XvrjCK/img69.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/VwsqFYz/img74.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/QmMHPtK/img84.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/dkd5rhr/img89.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/VBrhMzW/img90.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/N1j3mfF/img96.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/SmN6vCR/img100.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/xf2TvJR/img101.jpg", thumbnail: "" },
  { src: "https://i.ibb.co/YfRD5hb/img109.jpg", thumbnail: "" },
];
